import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

if (!process.env.SUPABASE_URL)         throw new Error("FATAL: Missing SUPABASE_URL");
if (!process.env.SUPABASE_SERVICE_KEY) throw new Error("FATAL: Missing SUPABASE_SERVICE_KEY");
if (!process.env.RESEND_API_KEY)       throw new Error("FATAL: Missing RESEND_API_KEY");

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

export { supabase };

const resend = new Resend(process.env.RESEND_API_KEY);

const buildEmailHtml = (auditResults, summary) => {
  const { totalCurrentSpend, optimizedMonthlySpend, annualWaste } = auditResults.summary;
  const { eligible, totalPotentialSavings, discountPercentage } = auditResults.credexOffer;
  const { redundancies, optimizations } = auditResults.flags;

  const redundancyItems = redundancies.map(r =>
    `<li>💸 ${r.message} <strong>(Save $${r.potentialSavings}/mo)</strong></li>`
  ).join('');

  const optimizationItems = optimizations.map(o =>
    `<li>⚡ ${o.message} <strong>(Save $${o.potentialSavings}/mo)</strong></li>`
  ).join('');

  const credexBanner = eligible ? `
    <div style="background:#f0fdf4;border:1px solid #86efac;border-radius:8px;padding:16px;margin:24px 0;">
      <h3 style="color:#16a34a;margin:0 0 8px">🎉 You qualify for Credex Credits!</h3>
      <p style="margin:0">Apply a <strong>${discountPercentage}% discount</strong> to bring your bill down further.</p>
    </div>` : '';

  return `
    <!DOCTYPE html>
    <html lang="en">
    <body style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1e293b;">
      <h2 style="color:#0f172a;border-bottom:2px solid #e2e8f0;padding-bottom:12px;">
        🔍 Credex AI Spend Audit
      </h2>
      <div style="display:flex;gap:12px;margin:20px 0;">
        <div style="flex:1;background:#fef2f2;border-radius:8px;padding:16px;text-align:center;">
          <p style="margin:0;font-size:12px;color:#64748b;text-transform:uppercase;">Current Spend</p>
          <p style="margin:4px 0 0;font-size:28px;font-weight:700;color:#dc2626;">$${totalCurrentSpend}<span style="font-size:14px;">/mo</span></p>
        </div>
        <div style="flex:1;background:#f0fdf4;border-radius:8px;padding:16px;text-align:center;">
          <p style="margin:0;font-size:12px;color:#64748b;text-transform:uppercase;">Optimized Spend</p>
          <p style="margin:4px 0 0;font-size:28px;font-weight:700;color:#16a34a;">$${optimizedMonthlySpend}<span style="font-size:14px;">/mo</span></p>
        </div>
        <div style="flex:1;background:#fffbeb;border-radius:8px;padding:16px;text-align:center;">
          <p style="margin:0;font-size:12px;color:#64748b;text-transform:uppercase;">Annual Waste</p>
          <p style="margin:4px 0 0;font-size:28px;font-weight:700;color:#d97706;">$${annualWaste}</p>
        </div>
      </div>
      ${credexBanner}
      <h3 style="color:#0f172a;">🔁 Redundancies Found</h3>
      <ul style="padding-left:20px;line-height:1.8;">${redundancyItems || '<li>None detected</li>'}</ul>
      <h3 style="color:#0f172a;">⚙️ Optimizations</h3>
      <ul style="padding-left:20px;line-height:1.8;">${optimizationItems || '<li>None detected</li>'}</ul>
      <div style="background:#f8fafc;border-left:4px solid #6366f1;padding:16px;border-radius:0 8px 8px 0;margin:24px 0;">
        <h3 style="margin:0 0 8px;color:#4f46e5;">📋 Executive Summary</h3>
        <p style="margin:0;line-height:1.7;">${summary}</p>
      </div>
      <p style="font-size:13px;color:#94a3b8;text-align:center;margin-top:32px;">
        Generated by Credex Audit · ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}
      </p>
    </body>
    </html>
  `;
};

// FIX: Added auditId as the first argument to match the controller!
export const captureLead = async (auditId, email, auditResults, summary) => {
  if (!email || !auditId) {
    console.log("[Lead Service] Missing email or auditId.");
    return null;
  }

  try {
    // FIX: Changed from upsert to update based on the ID we generated in Step 1
    const { data, error } = await supabase
      .from('leads')
      .update({ email: email, updated_at: new Date().toISOString() })
      .eq('id', auditId)
      .select()
      .single();

    if (error) throw new Error(`Supabase Error [${error.code}]: ${error.message}`);

    const { error: emailError } = await resend.emails.send({
      from: 'Credex Audit <onboarding@resend.dev>',
      to: email,
      subject: `Your Credex AI Audit is Ready — $${auditResults.credexOffer.totalPotentialSavings} in potential savings found`,
      html: buildEmailHtml(auditResults, summary)
    });

    if (emailError) {
      console.warn(`[Lead Service] Email delivery failed for ${email}:`, emailError.message);
    } else {
      console.log(`[Lead Service] Saved & emailed lead: ${email}`);
    }

    return data;

  } catch (err) {
    console.error("[Lead Service Error]:", err.message);
    return null;
  }
};